In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.svm import SVC

In [ ]:
"""
    Phase-1: k-nn & SVM
        3-Fold KNN
        Using Cross-Validate:
            Precision
            Recal
            F1
            Fit-Time
            Score-Time
"""

In [3]:
X = pd.read_csv("data/X.csv", sep=" ", header=None, dtype=float)
X = X.values

In [4]:
y = pd.read_csv("data/y_bush_vs_others.csv", header=None)
y_bush = y.values.ravel()
y = pd.read_csv("data/y_williams_vs_others.csv", header=None)
y_williams = y.values.ravel()

In [5]:
X.shape

(13233, 4096)

In [6]:
np.sum(y_bush)

530

In [7]:
np.sum(y_williams)

52

In [8]:
y_bush.shape

(13233,)

In [9]:
y_williams.shape

(13233,)

In [31]:
knn = KNeighborsClassifier(n_neighbors=3)

In [32]:
stratified_cv_results_knn = cross_validate(knn, X, y_bush, cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=int('5230')),
                                        scoring=('precision','recall','f1'), return_train_score=False, n_jobs=-1)

In [33]:
stratified_cv_results_knn

{'fit_time': array([14.07800794, 14.25460315, 14.01615739]),
 'score_time': array([1317.07241297, 1321.46224904, 1319.11155534]),
 'test_precision': array([0.36363636, 0.14285714, 0.15151515]),
 'test_recall': array([0.06779661, 0.02259887, 0.02840909]),
 'test_f1': array([0.11428571, 0.03902439, 0.04784689])}

In [25]:
svc = SVC(C=1e3, gamma=0.0001)

In [26]:
stratified_cv_results_svc = cross_validate(svc, X, y_bush, cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=int('5230')),
                                        scoring=('precision','recall','f1'), return_train_score=False, n_jobs=-1)

In [39]:
stratified_cv_results_svc

NameError: name 'stratified_cv_results_svc' is not defined

In [ ]:
import pickle
pickle.dump((stratified_cv_results_knn, stratified_cv_results_svc),open('res.pkl','wb'))

In [42]:
C_grid = [1e3, 5e3, 1e4, 5e4, 1e5]
gamma_grid = [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1]
hm_svc = {}

In [ ]:
for i in C_grid:
    for j in gamma_grid:
        s = str(i) + "__" + str(j)
        svc = SVC(C=i, gamma=j)
        stratified_cv_results_svc = cross_validate(svc, X, y_bush, cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=int('5230')),
                                        scoring=('precision','recall','f1'), return_train_score=False, n_jobs=-1)
        hm_svc[s] = stratified_cv_results_svc

In [22]:
with open('X.csv', 'r') as csvFile:
    reader = csv.reader(csvFile, delimiter =" ")
    i = 0
    arr = np.zeros((1,64*64))
    X = np.zeros((1,64,64))
    for row in reader:
        #print(row)
        arr[0] = row
        for j in range(64):
            for k in range(64):
                X[i][j][k] = arr[i][(j*64)+k]
        #print(row.shape)
        i += 1
        if i == 1:
            break

csvFile.close()
print(arr[0][-1])
print(X[0][63][63])
print (X.shape)
print(X)

0.04627987132353491
0.04627987132353491
(1, 64, 64)
[[[0.10635443 0.09975202 0.11191927 ... 0.10587563 0.10981539 0.11615669]
  [0.10215907 0.09380114 0.10587162 ... 0.11995357 0.11991167 0.12292239]
  [0.09190884 0.09576653 0.09597418 ... 0.13914043 0.13354873 0.14135496]
  ...
  [0.12394142 0.12649485 0.0633237  ... 0.11941977 0.10105848 0.10264012]
  [0.12405373 0.12356353 0.11986695 ... 0.11140404 0.11127479 0.10246083]
  [0.05743984 0.05721772 0.0587448  ... 0.04983379 0.05402631 0.04627987]]]
